"""예외 계층 — 사용자가 `except CronDoctorError` 한 줄로 잡을 수 있게.

다른 PC 작업 가이드:
    class CronDoctorError(Exception): ...
    class ParseError(CronDoctorError): ...
    class InvalidCronExpression(CronDoctorError): ...
    class UnreadableFileError(CronDoctorError): ...
    class SchemaViolation(CronDoctorError): ...
"""
# TODO: 다른 PC에서 예외 계층 구현
